version: 2


sources: 
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
        tests:
          - not_null
          - unique
                
              
      - name: sales
        identifier: raw_gz_sales
        columns:
        - name: date_date
        tests:
        - unique:
            column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
        tests:
          - unique
          - not_null
                  