version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales for greenweez /we have one row per production_id found in each ordrs_id
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: the order id
          - name: pdt_id
            description: product id
        tests:
          - unique:
              column_name: "(pdt_id || '-' || orders_id)"
      - name: product
        identifier: raw_gz_product
        description: the data of purches
        columns:
          - name: products_id
            description: primary key
            tests:
             - unique
             - not_null
      - name: ship
        identifier: raw_gz_ship
        description: the data of ship
        columns:
          - name: orders_id
            description: primark key
            tests:
              - unique
              - not_null